
#ifndef INC_LCD_H_
#define INC_LCD_H_

#include "stm32l1xx_hal.h"
#include <stdint.h>

/* Modular defines for Stone HMI JSON Commands */

// Common Start and End Markers for Stone HMI Commands
#define CMD_PREFIX 								"ST<{\"cmd_code\":\""
#define CMD_SUFFIX_TYPE 						"\",\"type\":\""
#define CMD_SUFFIX_WIDGET 						"\",\"widget\":\""
#define CMD_SUFFIX_TEXT 						"\",\"text\":\""
#define CMD_SUFFIX_VISIBLE 						"\",\"visible\":"
#define CMD_SUFFIX_END 							"\"}>ET"


// Specific Command Codes
#define CMD_CODE_SET_TEXT "set_text"
#define CMD_CODE_OPEN_WINDOW "open_win"
#define CMD_CODE_SET_VISIBLE "set_visible"

// Widget Types
#define WIDGET_TYPE_WINDOW "window"
#define WIDGET_TYPE_WIDGET "widget"


//#define CMD_PREFIX "ST<{\"cmd_code\":\"open_win\",\"type\":\"window\",\"widget\":\""
//#define CMD_SUFFIX "\"}>ET"

// ===================== Coordinate-to-Label Mapping =====================

// Structure for coordinate-to-label mapping
typedef struct {
    uint16_t x;
    uint16_t y;
    const char *label_name;
} CoordinateLabelMap;

// Predefined coordinate-to-label mapping
extern const CoordinateLabelMap label_mapping[];

// Retrieve label name from coordinates
const char* get_label_name(uint16_t x, uint16_t y);


// ===================== Index-to-Window Mapping =====================

// Structure for index-to-window mapping
typedef struct {
    uint16_t index;
    const char *window_name;
} IndexWindowMap;

// Predefined index-to-window mapping
extern const IndexWindowMap index_mapping[];

// Retrieve window name from index
const char* get_window_name_from_index(uint16_t index);


// Image Index Definitions with New Index Values (Old Index Value Commented)
#define NEW_PATIENT_IMAGE_INDEX        				1  // Old: 11
#define CONFIRM_NEW_PATIENT_IMAGE_INDEX        		2  // Old: 12
#define ERASING_OLD_DATA_IMAGE_INDEX        			3  // Old: 13
#define CLAMP_TUBES_IMAGE_INDEX_1        				4  // Old: 14
#define CLAMP_TUBES_IMAGE_INDEX_2        				5  // Old: 12
#define ALERT_SCREEN_IMAGE_INDEX        				6  // Old: 31
#define ERROR_SCREEN_IMAGE_INDEX        				7  // Old: 31
#define SETTINGS_SYS_1_IMAGE_INDEX        			8  // Old: 33
#define SETTINGS_SYS_2_IMAGE_INDEX        			9  // Old: 34
#define SETTINGS_SHUTDOWN_CONFIRM_IMAGE_INDEX        	10 // Old: 12
#define SHUTDOWN_IMAGE_INDEX        				11 // Old: 13
#define STAND_BY_IMAGE_INDEX        				12 // Old: 13
#define DATA_RETRIEVE_IMAGE_INDEX        			13 // Old: 6
#define RECALIBRATE_SENSOR_IMAGE_INDEX        		14 // Old: 6
#define POWER_ON_SELF_TEST_IMAGE_INDEX        		15 // Old: 10
#define REMOVE_SENSOR_TUBE_SCREEN_IMAGE_INDEX        	16 // Old: 6
#define SELF_TEST_SCREEN_IMAGE_INDEX        			17 // Old: 6
#define CONNECT_LUMEN_SCREEN_IMAGE_INDEX        		18 // Old: 9
#define START_SUCTION_SCREEN_IMAGE_INDEX        		19 // Old: 8
#define SUCTION_SCREEN_IMAGE_INDEX        			20 // Old: 13
#define SAVE_CHANGES_SCREEN_IMAGE_INDEX        		21 // Old: 11
#define SUCTION_SETTINGS_SCREEN_IMAGE_INDEX        		22 // Old: 11
#define CALIBRATION_SETTINGS_SCREEN_IMAGE_INDEX      	23 // Old: 11
#define PAUSE_MAIN_SCREEN_IMAGE_INDEX        			24 // Old: 9
#define PAUSE_CONNECTION_SCREEN_IMAGE_INDEX         	25 // Old: 11
#define JAR_CONNECTION_IMAGE_INDEX        			26 // Old: 6
#define REPLACE_LAVAGE_FLUID_IMAGE_INDEX        		27 // Old: 6
#define SENSOR_PLACEMENT_IMAGE_INDEX        			28 // Old: 6
#define DETACH_PATIENT_IMAGE_INDEX        			29 // Old: 15
#define DETACH_PATIENT_CONFIRM_IMAGE_INDEX          	30 // Old: 17
#define DETACH_PATIENT_STEPS_IMAGE_INDEX        		31 // Old: 6
#define SYSTEM_SHUT_IMAGE_INDEX        				32 // Old: 6
#define PLACE_SENSOR_TUBES_IMAGE_INDEX        		33 // Old: 6
#define CONNECT_SENSOR_JAR_TUBES_IMAGE_INDEX        	34 // Old: 6
#define EMERGENCY_SUCTION_IMAGE_INDEX        		35 // Old: 5
#define WELCOME_SCREEN_IMAGE_INDEX        			36 // Old: 6
#define UNCLAMP_TUBES_IMAGE_INDEX        			37 // Old: 16
#define PARAMETER_SCREEN_IMAGE_INDEX        		38 // Old: 17
#define SAVE_CONFIRMATION_IMAGE_INDEX        		39 // Old: 17
#define BEGIN_SUCTION_IMAGE_INDEX        			40 // Old: 19
#define INSIDE_ET_TUBE_BRUSHING_SUCTION_IMAGE_INDEX	41 // Old: 21
#define ORO_SUCTION_IMAGE_INDEX        			42 // Old: 23
#define SUB_SUCTION_IMAGE_INDEX        			43 // Old: 25
#define IDLE_SCREEN_IMAGE_INDEX        			44 // Old: 26
#define LAVAGE_SPRINKLING_IMAGE_INDEX        		45 // Old: 36
#define LAVAGE_SUCTION_IMAGE_INDEX        			46 // Old: 28
#define PAUSE_SCREEN_IMAGE_INDEX        			47 // Old: 29
#define PAUSE_AND_ALERT_SCREEN_IMAGE_INDEX        		48 // Old: 32
#define LEAKAGE_CHECK_AFTER_PAUSE_IMAGE_INDEX       	49 // Old: 30
#define SETTINGS_SCREEN_1_IMAGE_INDEX        				50 // Old: 12
#define SETTINGS_SCREEN_2_IMAGE_INDEX        				51 // Old: 12
#define BACK_CONFIRMATION_IMAGE_INDEX        		52 // Old: 35
#define PAUSE_LEAKAGE_CHECK_IMAGE_INDEX        		53 // Old: 13
#define DETECTING_SENSOR_IMAGE_INDEX        		54 // Old: 13
#define SETTINGS_SAVE_CONFIRMATION_IMAGE_INDEX      	55 // Old: 12
#define SETTINGS_SUCTION_OPTION_NOTE_IMAGE_INDEX    	56 // Old: 12
#define SETTINGS_EXTENDED_LOG_IMAGE_INDEX           	57 // Old: 0
#define SAVE_SETTINGS_AND_BEGIN_SUCTION_IMAGE_INDEX 	58 // Old: 37
#define ALERT_LOWBAT_SCREEN_IMAGE_INDEX        		59 // Old: 31


//Error definitions
#define ALERT_ORO_BLOOD_DETECTED						0
#define ALERT_SUBGLOTTIC_BLOOD_DETECTED					1
#define ALERT_ORO_PORT_BLOCK_DETECTED					2
#define ALERT_SUBGLOTTIC_PORT_BLOCK_DETECTED			3
#define ALERT_ORO_TUBE_REMOVAL_DETECTED					4
#define ALERT_SUBGLOTTIC_TUBE_REMOVAL_DETECTED			5
#define ALERT_ORO_NO_SECRETIONS_DETECTED				6
#define ALERT_SUBGLOTTIC_NO_SECRETIONS_DETECTED			7
#define ALERT_LEAKAGE_DETECTED							8
#define ALERT_CLAMP_NOT_REMOVED							9
#define ALERT_SENSOR_CALIBRATION_REQUIRED 				10
#define ALERT_SENSOR_CARD_NOT_RESPONDING				11
#define ALERT_REMOVE_TUBES								12
#define ALERT_SENSOR_CARD_CALIBRATION_FAIL				13
#define ALERT_CHECK_SUCTION_SOURCE						14

#define TOTAL_ALERT_MESSAGES 							15


//new defines for icons
#define BOX_YES_ICON_INDEX										1
#define CLEAR_BOX_YES_ICON_INDEX								0
#define BOX_NO_ICON_INDEX										1
#define CLEAR_BOX_NO_ICON_INDEX									0
#define DISPLAY_ICON											1
#define CLEAR_ICON												0

#define BATTERY_0_TO_20_ICON_INDEX_INACTIVE    					0  // Old: 0
#define BATTERY_21_TO_40_ICON_INDEX_INACTIVE   					0  // Old: 1
#define BATTERY_41_TO_60_ICON_INDEX_INACTIVE   					0  // Old: 2
#define BATTERY_61_TO_80_ICON_INDEX_INACTIVE   					0  // Old: 3
#define BATTERY_81_TO_100_ICON_INDEX_INACTIVE  					0  // Old: 4

#define BATTERY_0_TO_20_ICON_INDEX_ACTIVE      					1  // Old: 7
#define BATTERY_21_TO_40_ICON_INDEX_ACTIVE     					1  // Old: 8
#define BATTERY_41_TO_60_ICON_INDEX_ACTIVE     					1  // Old: 9
#define BATTERY_61_TO_80_ICON_INDEX_ACTIVE     					1  // Old: 10
#define BATTERY_81_TO_100_ICON_INDEX_ACTIVE    					1  // Old: 11

#define ROW_BOX_ICON_INDEX										1
#define ROW_CLEAR_ICON_INDEX									0//34



#define UNATTENDED_ALERT_ICON_INDEX								35
#define SELF_TEST_12_ICON_INDEX									14
#define SELF_TEST_24_ICON_INDEX									15
#define SELF_TEST_36_ICON_INDEX									16
#define SELF_TEST_48_ICON_INDEX									17
#define SELF_TEST_60_ICON_INDEX									18
#define SELF_TEST_72_ICON_INDEX									19
#define SELF_TEST_84_ICON_INDEX									20
#define SELF_TEST_100_ICON_INDEX								21
//#define BATTERY_0_TO_20_ICON_INDEX_INACTIVE						0
//#define BATTERY_21_TO_40_ICON_INDEX_INACTIVE					1
//#define BATTERY_41_TO_60_ICON_INDEX_INACTIVE					2
//#define BATTERY_61_TO_80_ICON_INDEX_INACTIVE					3
//#define BATTERY_81_TO_100_ICON_INDEX_INACTIVE					4
//#define BATTERY_0_TO_20_ICON_INDEX_ACTIVE						7
//#define BATTERY_21_TO_40_ICON_INDEX_ACTIVE						8
//#define BATTERY_41_TO_60_ICON_INDEX_ACTIVE						9
//#define BATTERY_61_TO_80_ICON_INDEX_ACTIVE						10
//#define BATTERY_81_TO_100_ICON_INDEX_ACTIVE						11
#define BUZZER_MUTE_ICON_INDEX 									5
#define BUZZER_ICON_INDEX 										6
#define LEAKAGE_TEST_ICON_9										16
#define LEAKAGE_TEST_ICON_8										17
#define LEAKAGE_TEST_ICON_7										18
#define LEAKAGE_TEST_ICON_6										19
#define LEAKAGE_TEST_ICON_5										20
#define LEAKAGE_TEST_ICON_4										21
#define LEAKAGE_TEST_ICON_3										22
#define LEAKAGE_TEST_ICON_2										23
#define LEAKAGE_TEST_ICON_1										24

#define ROW_BOX_ICON_LARGE_INDEX								33
#define ROW_CLEAR_ICON_LARGE_INDEX								34
#define LEFT_ICON_INDEX											14
#define RIGHT_ICON_INDEX										15
#define LEFT_FADED_ICON_INDEX									36
#define RIGHT_FADED_ICON_INDEX									37
#define LEFT_ICON_ERASE_INDEX									38
#define RIGHT_ICON_ERASE_INDEX									39
#define UP_ICON_INDEX											27
#define DOWN_ICON_INDEX											26
#define BOX_EMERGENCY_SUCTION_ICON_INDEX						30
#define CLEAR_BOX_EMERGENCY_SUCTION_ICON_INDEX					31

// X and Y coordinates
#define ROW_1_ICON_X											34
#define ROW_1_ICON_Y											85
#define ROW_2_ICON_X											34
#define ROW_2_ICON_Y											116
#define ROW_3_ICON_X											34
#define ROW_3_ICON_Y											144
#define ROW_4_ICON_X											34
#define ROW_4_ICON_Y											172
#define ROW_5_ICON_X											34
#define ROW_5_ICON_Y											200
/* Row for Page Two */
#define ROW_6_ICON_X											34
#define ROW_6_ICON_Y											85
#define ROW_7_ICON_X											34
#define ROW_7_ICON_Y											116
#define ROW_8_ICON_X											34
#define ROW_8_ICON_Y											144
#define ROW_9_ICON_X											34
#define ROW_9_ICON_Y											172
#define ROW_10_ICON_X											34
#define ROW_10_ICON_Y											200

#define ROW_1_LEFT_ICON_X										278
#define ROW_1_LEFT_ICON_Y										93
#define ROW_1_RIGHT_ICON_X										329
#define ROW_1_RIGHT_ICON_Y										93
#define ROW_2_LEFT_ICON_X										278
#define ROW_2_LEFT_ICON_Y										121
#define ROW_2_RIGHT_ICON_X										329
#define ROW_2_RIGHT_ICON_Y										121
#define ROW_3_LEFT_ICON_X										278
#define ROW_3_LEFT_ICON_Y										149
#define ROW_3_RIGHT_ICON_X										329
#define ROW_3_RIGHT_ICON_Y										149
#define ROW_4_LEFT_ICON_X										278
#define ROW_4_LEFT_ICON_Y										177
#define ROW_4_RIGHT_ICON_X										329
#define ROW_4_RIGHT_ICON_Y										177
#define ROW_5_LEFT_ICON_X										278
#define ROW_5_LEFT_ICON_Y										205
#define ROW_5_RIGHT_ICON_X										329
#define ROW_5_RIGHT_ICON_Y										205
#define ROW_6_LEFT_ICON_X										278
#define ROW_6_LEFT_ICON_Y										93
#define ROW_6_RIGHT_ICON_X										329
#define ROW_6_RIGHT_ICON_Y										93
#define ROW_7_LEFT_ICON_X										278
#define ROW_7_LEFT_ICON_Y										121
#define ROW_7_RIGHT_ICON_X										329
#define ROW_7_RIGHT_ICON_Y										121
#define ROW_8_LEFT_ICON_X										278
#define ROW_8_LEFT_ICON_Y										149
#define ROW_8_RIGHT_ICON_X										329
#define ROW_8_RIGHT_ICON_Y										149



#define UP_ICON_X												40
#define UP_ICON_Y												80
#define DOWN_ICON_X												40
#define DOWN_ICON_Y												210
#define BUZZER_ICON_X											6
#define BUZZER_ICON_Y											2

#define OPTION_TEXT_X											395
#define OPTION_TEXT_Y											244
#define BACK_TEXT_X												40
#define BACK_TEXT_Y												244
#define PAUSE_TEXT_X											212
#define PAUSE_TEXT_Y											196

#define ALERT_SUCTION_SETTINGS_TEXT_1_X							166
#define ALERT_SUCTION_SETTINGS_TEXT_1_Y							30
#define ALERT_SUCTION_SETTINGS_TEXT_2_X							100
#define ALERT_SUCTION_SETTINGS_TEXT_2_Y							100
#define ALERT_SUCTION_SETTINGS_TEXT_3_X							140
#define ALERT_SUCTION_SETTINGS_TEXT_3_Y							130
#define ALERT_SUCTION_SETTINGS_TEXT_4_X							143
#define ALERT_SUCTION_SETTINGS_TEXT_4_Y							198

#define CONFIRM_NEW_PATIENT_TEXT1_X								134
#define CONFIRM_NEW_PATIENT_TEXT1_Y								100
#define CONFIRM_NEW_PATIENT_TEXT2_X								80
#define CONFIRM_NEW_PATIENT_TEXT2_Y								130
#define CONFIRM_NEW_PATIENT_TEXT3_X								148
#define CONFIRM_NEW_PATIENT_TEXT3_Y								198

#define ERASING_FLASH_TEXT1_X									64
#define ERASING_FLASH_TEXT1_Y									100
#define ERASING_FLASH_TEXT2_X									156
#define ERASING_FLASH_TEXT2_Y									130

#define START_SUCTION_TEXT_1_X									162
#define START_SUCTION_TEXT_1_Y									48
#define START_SUCTION_TEXT_2_X									118
#define START_SUCTION_TEXT_2_Y									196

#define IDLE_SCREEN_TEXT_1_X									60
#define IDLE_SCREEN_TEXT_1_Y									95
#define IDLE_SCREEN_TEXT_2_X									60
#define IDLE_SCREEN_TEXT_2_Y									155
#define IDLE_SCREEN_TEXT_3_X									305
#define IDLE_SCREEN_TEXT_3_Y									102
#define IDLE_SCREEN_TEXT_4_X									351
#define IDLE_SCREEN_TEXT_4_Y									102
#define IDLE_SCREEN_TEXT_5_X									399
#define IDLE_SCREEN_TEXT_5_Y									102
#define IDLE_SCREEN_TEXT_6_X									305
#define IDLE_SCREEN_TEXT_6_Y									162
#define IDLE_SCREEN_TEXT_7_X									351
#define IDLE_SCREEN_TEXT_7_Y									162
#define IDLE_SCREEN_TEXT_8_X									399
#define IDLE_SCREEN_TEXT_8_Y									162
#define IDLE_SCREEN_TEXT_9_X									263
#define IDLE_SCREEN_TEXT_9_Y									161

#define IDLE_SCREEN_NUM_1_X										270
#define IDLE_SCREEN_NUM_1_Y										90
#define IDLE_SCREEN_NUM_2_X										270
#define IDLE_SCREEN_NUM_2_Y										150

#define SETTING_PRESSURE_TEXT_1_X								107
#define SETTING_PRESSURE_TEXT_1_Y								90
#define SETTING_PRESSURE_TEXT_2_X								310
#define SETTING_PRESSURE_TEXT_2_Y								146
#define SETTING_PRESSURE_TEXT_3_X								200
#define SETTING_PRESSURE_TEXT_3_Y								126

#define CURRENT_SETTING_PRESSURE_VAL_X							123
#define CURRENT_SETTING_PRESSURE_VAL_Y							126
#define SUCTION_TARGET_PRESSURE_VAL_X							233
#define SUCTION_TARGET_PRESSURE_VAL_Y							126

#define SPRINKILING_TEXT_1_X									114
#define SPRINKILING_TEXT_1_Y									100
#define SPRINKILING_TEXT_2_X									170
#define SPRINKILING_TEXT_2_Y									130

#define SUCTION_TEXT_1_X										144
#define SUCTION_TEXT_1_Y										90
#define SUCTION_TEXT_2_X										254
#define SUCTION_TEXT_2_Y										146

#define SUCTION_PRESSURE_VAL_X									168
#define SUCTION_PRESSURE_VAL_Y									126

#define ORAL_SUCTION_TEXT_X										188
#define ORAL_SUCTION_TEXT_Y										44
#define ORO_SUCTION_TEXT_X										134
#define ORO_SUCTION_TEXT_Y										44
#define SUBGLOTTIC_SUCTION_TEXT_X								152
#define SUBGLOTTIC_SUCTION_TEXT_Y								44
#define INSIDE_ET_TUBE_SUCTION_TEXT_X							152
#define INSIDE_ET_TUBE_SUCTION_TEXT_Y							44
#define BRUSHING_SUCTION_TEXT_X									188
#define BRUSHING_SUCTION_TEXT_Y									44

#define ORAL_PORT_BLOCK_TEXT_X									150
#define ORAL_PORT_BLOCK_TEXT_Y									44
#define ORO_PORT_BLOCK_TEXT_X									96
#define ORO_PORT_BLOCK_TEXT_Y									44
#define SUBGLOTTIC_PORT_BLOCK_TEXT_X							114
#define SUBGLOTTIC_PORT_BLOCK_TEXT_Y							44
//=========================================================================
#define ORO_MANDATORY_SUCTION_X									22
#define ORO_MANDATORY_SUCTION_Y									44

#define LAVAGE_TEXT_X											196
#define LAVAGE_TEXT_Y											44

#define POWER_ON_TEST_X											50
#define POWER_ON_TEST_Y											190

#define PHARYNGEAL_OPTION										0
#define SUBGLOTTIC_OPTION										1
#define LAVAGE_OPTION											2

#define SETTINGS_SUCTION_ORO_VAL_X								298
#define SETTINGS_SUCTION_ORO_VAL_Y								93
#define SETTINGS_SUCTION_SUB_VAL_X								298
#define SETTINGS_SUCTION_SUB_VAL_Y								93
#define SETTINGS_LAVAGE_VAL_X									298
#define SETTINGS_LAVAGE_VAL_Y									93

#define SETTINGS_ORO_PORT_BLOCK_VAL_X							298
#define SETTINGS_ORO_PORT_BLOCK_VAL_Y							149
#define SETTINGS_SUB_PORT_BLOCK_VAL_X							298
#define SETTINGS_SUB_PORT_BLOCK_VAL_Y							149

#define DETACH_PATIENT_CONFIRM_TEXT_1_X							162
#define DETACH_PATIENT_CONFIRM_TEXT_1_Y							124
#define DETACH_PATIENT_STEPS_TEXT_1_X							90
#define DETACH_PATIENT_STEPS_TEXT_1_Y							48
#define DETACH_PATIENT_STEPS_TEXT_2_X							90
#define DETACH_PATIENT_STEPS_TEXT_2_Y							84
#define DETACH_PATIENT_STEPS_TEXT_3_X							90
#define DETACH_PATIENT_STEPS_TEXT_3_Y							112
#define DETACH_PATIENT_STEPS_TEXT_4_X							90
#define DETACH_PATIENT_STEPS_TEXT_4_Y							140
#define DETACH_PATIENT_STEPS_TEXT_5_X							90
#define DETACH_PATIENT_STEPS_TEXT_5_Y							168
#define DETACH_PATIENT_STEPS_TEXT_6_X							90
#define DETACH_PATIENT_STEPS_TEXT_6_Y							196

#define STAND_BY_TEXT_1_X										90
#define STAND_BY_TEXT_1_Y										58
#define STAND_BY_TEXT_2_X										80
#define STAND_BY_TEXT_2_Y										76
#define STAND_BY_TEXT_3_X										90
#define STAND_BY_TEXT_3_Y										121
#define STAND_BY_TEXT_4_X										90
#define STAND_BY_TEXT_4_Y										149
#define STAND_BY_TEXT_5_X										280
#define STAND_BY_TEXT_5_Y										58
#define STAND_BY_TEXT_6_X										314
#define STAND_BY_TEXT_6_Y										70
#define STAND_BY_TEXT_7_X										361
#define STAND_BY_TEXT_7_Y										70
#define STAND_BY_TEXT_8_X										408
#define STAND_BY_TEXT_8_Y										70
#define STAND_BY_TEXT_9_X										60
#define STAND_BY_TEXT_9_Y										198

#define SYSTEM_SHUTDOWN_TEXT_1_X 								95
#define SYSTEM_SHUTDOWN_TEXT_1_Y 								110
#define SYSTEM_SHUTDOWN_TEXT_2_X 								130
#define SYSTEM_SHUTDOWN_TEXT_2_Y 								198

#define EMERGENCY_SUCTION_TEXT_1_X								50
#define EMERGENCY_SUCTION_TEXT_1_Y								48
#define EMERGENCY_SUCTION_TEXT_2_X								50
#define EMERGENCY_SUCTION_TEXT_2_Y								93
#define EMERGENCY_SUCTION_TEXT_3_X								50
#define EMERGENCY_SUCTION_TEXT_3_Y								121
#define EMERGENCY_SUCTION_TEXT_4_X								50
#define EMERGENCY_SUCTION_TEXT_4_Y								149
#define EMERGENCY_SUCTION_TEXT_5_X								50
#define EMERGENCY_SUCTION_TEXT_5_Y								177
#define EMERGENCY_SUCTION_TEXT_6_X								50
#define EMERGENCY_SUCTION_TEXT_6_Y								213

#define EMERGENCY_SUCTION_BOX_SUCTION_ICON_X					34
#define EMERGENCY_SUCTION_BOX_SUCTION_ICON_Y					86
#define EMERGENCY_SUCTION_BOX_LAVAGE_ICON_X						34
#define EMERGENCY_SUCTION_BOX_LAVAGE_ICON_Y						114
#define EMERGENCY_INSIDE_ET_TUBE_BOX_ICON_X						34
#define EMERGENCY_INSIDE_ET_TUBE_BOX_ICON_Y						142
#define EMERGENCY_BRUSHING_BOX_ICON_X							34
#define EMERGENCY_BRUSHING_BOX_ICON_Y							170

#define DETECTING_SENSOR_TEXT1_X								120
#define DETECTING_SENSOR_TEXT1_Y								100
#define DETECTING_SENSOR_TEXT2_X								156
#define DETECTING_SENSOR_TEXT2_Y								130

#define RECALIBRATE_SENSOR_TEXT1_X								90
#define RECALIBRATE_SENSOR_TEXT1_Y								100
#define RECALIBRATE_SENSOR_TEXT2_X								156
#define RECALIBRATE_SENSOR_TEXT2_Y								130

#define ENTER_EXTENDED_LOG_ACCESS_TEXT1_X						140
#define ENTER_EXTENDED_LOG_ACCESS_TEXT1_Y						90
#define ENTER_EXTENDED_LOG_ACCESS_TEXT2_X						174
#define ENTER_EXTENDED_LOG_ACCESS_TEXT2_Y						120
#define ENTER_EXTENDED_LOG_ACCESS_TEXT3_X						100
#define ENTER_EXTENDED_LOG_ACCESS_TEXT3_Y						198

#define UNATTENDED_ALERT_ICON_X									198
#define UNATTENDED_ALERT_ICON_Y									244

#define CLAMP_TUBE_TEXT1_X										162
#define CLAMP_TUBE_TEXT1_Y										48
#define CLAMP_TUBE_TEXT2_X										90
#define CLAMP_TUBE_TEXT2_Y										110
#define CLAMP_TUBE_TEXT3_X										120
#define CLAMP_TUBE_TEXT3_Y										130
#define CLAMP_TUBE_TEXT4_X										148
#define CLAMP_TUBE_TEXT4_Y										198
#define CLAMP_TUBE_TEXT5_X										80
#define CLAMP_TUBE_TEXT5_Y										198

#define VERIFY_NEW_PATIENT_TEXT1_X								168
#define VERIFY_NEW_PATIENT_TEXT1_Y								48
#define VERIFY_NEW_PATIENT_TEXT2_X								120
#define VERIFY_NEW_PATIENT_TEXT2_Y								198
#define VERIFY_NEW_PATIENT_BOX_YES_ICON_X						182
#define VERIFY_NEW_PATIENT_BOX_YES_ICON_Y						94
#define VERIFY_NEW_PATIENT_BOX_NO_ICON_X						181//182
#define VERIFY_NEW_PATIENT_BOX_NO_ICON_Y						137
#define VERIFY_NEW_PATIENT_YES_X								209
#define VERIFY_NEW_PATIENT_YES_Y								96
#define VERIFY_NEW_PATIENT_NO_X									215
#define VERIFY_NEW_PATIENT_NO_Y									139

#define VERIFY_PAUSE_LEAKAGE_CHECK_BOX_YES_ICON_X				182
#define VERIFY_PAUSE_LEAKAGE_CHECK_BOX_YES_ICON_Y				94
#define VERIFY_PAUSE_LEAKAGE_CHECK_YES_X						209
#define VERIFY_PAUSE_LEAKAGE_CHECK_Y							96
#define VERIFY_PAUSE_LEAKAGE_CHECK_NO_X							215
#define VERIFY_PAUSE_LEAKAGE_CHECK_NO_Y							139

#define VERIFY_PAUSE_LEAKAGE_CHECK_TEXT1_X						108
#define VERIFY_PAUSE_LEAKAGE_CHECK_TEXT1_Y						48
#define VERIFY_PAUSE_LEAKAGE_CHECK_TEXT2_X						130
#define VERIFY_PAUSE_LEAKAGE_CHECK_TEXT2_Y						198
#define VERIFY_PAUSE_LEAKAGE_CHECK_UP_ICON_X					284
#define VERIFY_PAUSE_LEAKAGE_CHECK_UP_ICON_Y					98
#define VERIFY_PAUSE_LEAKAGE_CHECK_DOWN_ICON_X					284
#define VERIFY_PAUSE_LEAKAGE_CHECK_DOWN_ICON_Y					144
#define VERIFY_PAUSE_LEAKAGE_CHECK_BOX_YES_ICON_X				182
#define VERIFY_PAUSE_LEAKAGE_CHECK_BOX_YES_ICON_Y				94
#define VERIFY_PAUSE_LEAKAGE_CHECK_BOX_NO_ICON_X				182
#define VERIFY_PAUSE_LEAKAGE_CHECK_BOX_NO_ICON_Y				137
#define VERIFY_PAUSE_LEAKAGE_CHECK_YES_X						209
#define VERIFY_PAUSE_LEAKAGE_CHECK_YES_Y						96
#define VERIFY_PAUSE_LEAKAGE_CHECK_NO_X							215
#define VERIFY_PAUSE_LEAKAGE_CHECK_NO_Y							139

#define SYSTEM_PAUSE_TEXT_1X									140
#define SYSTEM_PAUSE_TEXT_1Y									110
#define SYSTEM_PAUSE_TEXT_2X									150
#define SYSTEM_PAUSE_TEXT_2Y									200

#define RECTANGLE_BOX_FOR_CONTENT_DISPLAY_INDEX					32
#define RECTANGLE_BOX_ICON_X									65
#define RECTANGLE_BOX_ICON_Y									80

#define BATTERY_TEXT_X											410
#define BATTERY_TEXT_Y											4
#define BATTERY_ICON_X											450
#define BATTERY_ICON_Y											5

#define LEAKAGE_TEST_ICON_X										217
#define LEAKAGE_TEST_ICON_Y										92

#define MANDATORY_SUCTION_TEXT_X								272
#define MANDATORY_SUCTION_TEXT_Y								244

#define START_TILE_TEXT_X										157
#define START_TILE_TEXT_Y										244

#define SELF_TEST_ICON_X										217
#define SELF_TEST_ICON_Y										92
#define SELF_TEST_TEXT_1_X										162
#define SELF_TEST_TEXT_1_Y										48
#define SELF_TEST_TEXT_2_X										214
#define SELF_TEST_TEXT_2_Y										150
#define SELF_TEST_TEXT_3_X										254
#define SELF_TEST_TEXT_3_Y										150
#define SELF_TEST_TEXT_4_X										110
#define SELF_TEST_TEXT_4_Y										189
#define SELF_TEST_TEXT_5_X										60
#define SELF_TEST_TEXT_5_Y										198

#define PORT_SETTINGS_CONFIRM_TEXT_R1C1_X						18
#define PORT_SETTINGS_CONFIRM_TEXT_R1C1_Y						66
#define PORT_SETTINGS_CONFIRM_TEXT_R2C1_X						23
#define PORT_SETTINGS_CONFIRM_TEXT_R2C1_Y						96
#define PORT_SETTINGS_CONFIRM_TEXT_R3C1_X						23
#define PORT_SETTINGS_CONFIRM_TEXT_R3C1_Y						126
#define PORT_SETTINGS_CONFIRM_TEXT_R4C1_X						23
#define PORT_SETTINGS_CONFIRM_TEXT_R4C1_Y						156
#define PORT_SETTINGS_CONFIRM_TEXT_R5C1_X						23
#define PORT_SETTINGS_CONFIRM_TEXT_R5C1_Y						186
#define PORT_SETTINGS_CONFIRM_TEXT_1_X							105//135
#define PORT_SETTINGS_CONFIRM_TEXT_1_Y							35
#define PORT_SETTINGS_CONFIRM_TEXT_2_X							30
#define PORT_SETTINGS_CONFIRM_TEXT_2_Y							215

#define PORT_SETTINGS_CONFIRM_TEXT_R1C2_X						142
#define PORT_SETTINGS_CONFIRM_TEXT_R1C2_Y						66
#define PORT_SETTINGS_CONFIRM_TEXT_R1C3_X						208
#define PORT_SETTINGS_CONFIRM_TEXT_R1C3_Y						66
#define PORT_SETTINGS_CONFIRM_TEXT_R1C4_X						293
#define PORT_SETTINGS_CONFIRM_TEXT_R1C4_Y						66
#define PORT_SETTINGS_CONFIRM_TEXT_R1C5_X						388
#define PORT_SETTINGS_CONFIRM_TEXT_R1C5_Y						66

#define PORT_SETTINGS_CONFIRM_TEXT_R2C2_X						145
#define PORT_SETTINGS_CONFIRM_TEXT_R2C2_Y						96
#define PORT_SETTINGS_CONFIRM_TEXT_R2C3_X						230
#define PORT_SETTINGS_CONFIRM_TEXT_R2C3_Y						96
#define PORT_SETTINGS_CONFIRM_TEXT_R2C4_X						315
#define PORT_SETTINGS_CONFIRM_TEXT_R2C4_Y						96
#define PORT_SETTINGS_CONFIRM_TEXT_R2C5_X						400
#define PORT_SETTINGS_CONFIRM_TEXT_R2C5_Y						96

#define PORT_SETTINGS_CONFIRM_NUM_R3C23_X						130
#define PORT_SETTINGS_CONFIRM_NUM_R3C23_Y						126
#define PORT_SETTINGS_CONFIRM_NUM_R3C24_X						220
#define PORT_SETTINGS_CONFIRM_NUM_R3C24_Y						126
#define PORT_SETTINGS_CONFIRM_NUM_R3C4_X						305
#define PORT_SETTINGS_CONFIRM_NUM_R3C4_Y						126
#define PORT_SETTINGS_CONFIRM_NUM_R3C5_X						390
#define PORT_SETTINGS_CONFIRM_NUM_R3C5_Y						126
#define PORT_SETTINGS_CONFIRM_TEXT_R3C23_X						160
#define PORT_SETTINGS_CONFIRM_TEXT_R3C23_Y						126
#define PORT_SETTINGS_CONFIRM_TEXT_R3C24_X						250
#define PORT_SETTINGS_CONFIRM_TEXT_R3C24_Y						126
#define PORT_SETTINGS_CONFIRM_TEXT_R3C4_X						335
#define PORT_SETTINGS_CONFIRM_TEXT_R3C4_Y						126
#define PORT_SETTINGS_CONFIRM_TEXT_R3C5_X						420
#define PORT_SETTINGS_CONFIRM_TEXT_R3C5_Y						126

#define PORT_SETTINGS_CONFIRM_NUM_R4C233_X						145
#define PORT_SETTINGS_CONFIRM_NUM_R4C233_Y						156
#define PORT_SETTINGS_CONFIRM_NUM_R4C234_X						215
#define PORT_SETTINGS_CONFIRM_NUM_R4C234_Y						156
#define PORT_SETTINGS_CONFIRM_NUM_R4C235_X						305
#define PORT_SETTINGS_CONFIRM_NUM_R4C235_Y						156
#define PORT_SETTINGS_CONFIRM_NUM_R4C5_X						390
#define PORT_SETTINGS_CONFIRM_NUM_R4C5_Y						156
#define PORT_SETTINGS_CONFIRM_TEXT_R4C234_X						250
#define PORT_SETTINGS_CONFIRM_TEXT_R4C234_Y						156
#define PORT_SETTINGS_CONFIRM_TEXT_R4C235_X						335
#define PORT_SETTINGS_CONFIRM_TEXT_R4C235_Y						156
#define PORT_SETTINGS_CONFIRM_TEXT_R4C5_X						420
#define PORT_SETTINGS_CONFIRM_TEXT_R4C5_Y						156

#define PORT_SETTINGS_CONFIRM_TEXT_R5C2_X						145
#define PORT_SETTINGS_CONFIRM_TEXT_R5C2_Y						186
#define PORT_SETTINGS_CONFIRM_TEXT_R5C3_X						230
#define PORT_SETTINGS_CONFIRM_TEXT_R5C3_Y						186
#define PORT_SETTINGS_CONFIRM_TEXT_R5C4_X						315
#define PORT_SETTINGS_CONFIRM_TEXT_R5C4_Y						186
#define PORT_SETTINGS_CONFIRM_TEXT_R5C5_X						400
#define PORT_SETTINGS_CONFIRM_TEXT_R5C5_Y						186

/******* Alerts and Errors **********/
#define ALERT_CLEARABLE_TEXT_1_X								166
#define ALERT_CLEARABLE_TEXT_1_Y								48
#define ALERT_CLEARABLE_TEXT_2_X								133
#define ALERT_CLEARABLE_TEXT_2_Y								228

#define ALERT_CLEARABLE_MESSAGE_1_X_1							114
#define ALERT_CLEARABLE_MESSAGE_1_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_2_X_1							60
#define ALERT_CLEARABLE_MESSAGE_2_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_3_X_1							78
#define ALERT_CLEARABLE_MESSAGE_3_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_4_X_1							126
#define ALERT_CLEARABLE_MESSAGE_4_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_5_X_1							72
#define ALERT_CLEARABLE_MESSAGE_5_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_6_X_1							90
#define ALERT_CLEARABLE_MESSAGE_6_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_7_X_1							96
#define ALERT_CLEARABLE_MESSAGE_7_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_8_X_1							42
#define ALERT_CLEARABLE_MESSAGE_8_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_9_X_1							60
#define ALERT_CLEARABLE_MESSAGE_9_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_10_X_1							42
#define ALERT_CLEARABLE_MESSAGE_10_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_11_X_1			 				120
#define ALERT_CLEARABLE_MESSAGE_11_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_12_X_1							66
#define ALERT_CLEARABLE_MESSAGE_12_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_13_X_1							84
#define ALERT_CLEARABLE_MESSAGE_13_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_14_X_1							126
#define ALERT_CLEARABLE_MESSAGE_14_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_15_X_1							103
#define ALERT_CLEARABLE_MESSAGE_15_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_16_X_1							138
#define ALERT_CLEARABLE_MESSAGE_16_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_17_X_1							78
#define ALERT_CLEARABLE_MESSAGE_17_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_18_X_1							85
#define ALERT_CLEARABLE_MESSAGE_18_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_19_X_1							126
#define ALERT_CLEARABLE_MESSAGE_19_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_20_X_1							132
#define ALERT_CLEARABLE_MESSAGE_20_Y_1							130
#define ALERT_CLEARABLE_MESSAGE_21_X_1							103
#define ALERT_CLEARABLE_MESSAGE_21_Y_1							130

#define ALERT_CLEARABLE_MESSAGE_1_X_2							99
#define ALERT_CLEARABLE_MESSAGE_1_Y_2							160//200
#define ALERT_CLEARABLE_MESSAGE_2_X_2							45
#define ALERT_CLEARABLE_MESSAGE_2_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_3_X_2							63
#define ALERT_CLEARABLE_MESSAGE_3_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_4_X_2							45//100
#define ALERT_CLEARABLE_MESSAGE_4_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_5_X_2							45//100
#define ALERT_CLEARABLE_MESSAGE_5_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_6_X_2							45//100
#define ALERT_CLEARABLE_MESSAGE_6_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_7_X_2							81
#define ALERT_CLEARABLE_MESSAGE_7_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_8_X_2							27
#define ALERT_CLEARABLE_MESSAGE_8_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_9_X_2							45
#define ALERT_CLEARABLE_MESSAGE_9_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_10_X_2							37
#define ALERT_CLEARABLE_MESSAGE_10_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_11_X_2			 				100//140
#define ALERT_CLEARABLE_MESSAGE_11_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_12_X_2							100//140
#define ALERT_CLEARABLE_MESSAGE_12_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_13_X_2							100//140
#define ALERT_CLEARABLE_MESSAGE_13_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_14_X_2							111
#define ALERT_CLEARABLE_MESSAGE_14_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_15_X_2							90//113
#define ALERT_CLEARABLE_MESSAGE_15_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_16_X_2							170
#define ALERT_CLEARABLE_MESSAGE_16_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_17_X_2							33//63
#define ALERT_CLEARABLE_MESSAGE_17_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_18_X_2							70
#define ALERT_CLEARABLE_MESSAGE_18_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_19_X_2							111
#define ALERT_CLEARABLE_MESSAGE_19_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_20_X_2							117
#define ALERT_CLEARABLE_MESSAGE_20_Y_2							160
#define ALERT_CLEARABLE_MESSAGE_21_X_2							115//150
#define ALERT_CLEARABLE_MESSAGE_21_Y_2							160

#define ALERT_LOW_BATTERY_TEXT_1_X								154
#define ALERT_LOW_BATTERY_TEXT_1_Y								130
#define ALERT_LOW_BATTERY_TEXT_2_X								162
#define ALERT_LOW_BATTERY_TEXT_2_Y								208

#define ALERT_NON_CLEARABLE_TEXT_1_X							108
#define ALERT_NON_CLEARABLE_TEXT_1_Y							68
#define ALERT_NON_CLEARABLE_TEXT_2_X							114
#define ALERT_NON_CLEARABLE_TEXT_2_Y							150
#define ALERT_NON_CLEARABLE_TEXT_3_X							133
#define ALERT_NON_CLEARABLE_TEXT_3_Y							228

#define ALERT_NON_CLEARABLE_ERROR_CODE_X						300
#define ALERT_NON_CLEARABLE_ERROR_CODE_Y						68

#define SETTINGS_MAIN_TEXT_1_X									50
#define SETTINGS_MAIN_TEXT_1_Y									48
#define SETTINGS_MAIN_TEXT_2_X									50
#define SETTINGS_MAIN_TEXT_2_Y									93
#define SETTINGS_MAIN_TEXT_3_X									50
#define SETTINGS_MAIN_TEXT_3_Y									121
#define SETTINGS_MAIN_TEXT_4_X									50
#define SETTINGS_MAIN_TEXT_4_Y									149
#define SETTINGS_MAIN_TEXT_5_X									50
#define SETTINGS_MAIN_TEXT_5_Y									177
#define SETTINGS_MAIN_TEXT_6_X									50
#define SETTINGS_MAIN_TEXT_6_Y									205
#define SETTINGS_MAIN_TEXT_7_X									50
#define SETTINGS_MAIN_TEXT_7_Y									213

#define SETTING_SUCTION_SETTINGS_TEXT_1_X						50
#define SETTING_SUCTION_SETTINGS_TEXT_1_Y						48
#define SETTING_SUCTION_SETTINGS_TEXT_2_X						50
#define SETTING_SUCTION_SETTINGS_TEXT_2_Y						93
#define SETTING_SUCTION_SETTINGS_NUM_1_X						298
#define SETTING_SUCTION_SETTINGS_NUM_1_Y						93
#define	SETTING_SUCTION_SETTINGS_TEXT_3_X						344
#define	SETTING_SUCTION_SETTINGS_TEXT_3_Y						93
#define	SETTING_SUCTION_SETTINGS_TEXT_4_X						50
#define	SETTING_SUCTION_SETTINGS_TEXT_4_Y						121
#define	SETTING_SUCTION_SETTINGS_NUM_2_X						298
#define	SETTING_SUCTION_SETTINGS_NUM_2_Y						121
#define	SETTING_SUCTION_SETTINGS_TEXT_5_X						344
#define	SETTING_SUCTION_SETTINGS_TEXT_5_Y						121
#define	SETTING_SUCTION_SETTINGS_TEXT_6_X						50
#define	SETTING_SUCTION_SETTINGS_TEXT_6_Y						149
#define	SETTING_SUCTION_SETTINGS_NUM_3_X						298
#define	SETTING_SUCTION_SETTINGS_NUM_3_Y						149
#define	SETTING_SUCTION_SETTINGS_TEXT_7_X						344
#define	SETTING_SUCTION_SETTINGS_TEXT_7_Y						149
#define	SETTING_SUCTION_SETTINGS_TEXT_8_X						50
#define	SETTING_SUCTION_SETTINGS_TEXT_8_Y						177
#define	SETTING_SUCTION_SETTINGS_NUM_4_X						298
#define	SETTING_SUCTION_SETTINGS_NUM_4_Y						177
#define	SETTING_SUCTION_SETTINGS_TEXT_9_X						344
#define	SETTING_SUCTION_SETTINGS_TEXT_9_Y						177
#define SETTING_SUCTION_SETTINGS_TEXT_10_X						50
#define SETTING_SUCTION_SETTINGS_TEXT_10_Y						215

#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_1_X				100
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_1_Y				35
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_2_X				90
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_2_Y				71
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_3_X				90
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_3_Y				94
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_4_X				354
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_4_Y				94
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_5_X				90
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_5_Y				117
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_6_X				70
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_6_Y				198
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_7_X				354
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_7_Y				71
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_8_X				354
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_8_Y				117
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_9_X				90
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_9_Y				141
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_10_X				354
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_TEXT_10_Y				141

#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_1_X				324
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_1_Y				71
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_2_X				324
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_2_Y				94
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_3_X				324
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_3_Y				117
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_4_X				324
#define SETTINGS_SUCTION_SETTINGS_CONFIRM_NUM_4_Y				141

#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_1_X				90
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_1_Y				48
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_2_X				90
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_2_Y				99
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_3_X				324
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_3_Y				99
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_4_X				75
#define SETTING_SUCTION_INTERVAL_CONFIRM_TEXT_4_Y				198
#define SETTING_SUCTION_INTERVAL_CONFIRM_NUM_1_X				284
#define SETTING_SUCTION_INTERVAL_CONFIRM_NUM_1_Y				99

#define	SETTINGS_PHARYNGEAL_TEXT_1_X							50
#define	SETTINGS_PHARYNGEAL_TEXT_1_Y							48
#define	SETTINGS_PHARYNGEAL_TEXT_2_X							50
#define	SETTINGS_PHARYNGEAL_TEXT_2_Y							93
#define	SETTINGS_PHARYNGEAL_TEXT_3_X							50
#define	SETTINGS_PHARYNGEAL_TEXT_3_Y							121
#define	SETTINGS_PHARYNGEAL_TEXT_4_X							344
#define	SETTINGS_PHARYNGEAL_TEXT_4_Y							121
#define	SETTINGS_PHARYNGEAL_TEXT_5_X							50
#define	SETTINGS_PHARYNGEAL_TEXT_5_Y							149
#define	SETTINGS_PHARYNGEAL_TEXT_6_X							50
#define	SETTINGS_PHARYNGEAL_TEXT_6_Y							198

#define	SETTINGS_PHARYNGEAL_NUM_1_X								298
#define	SETTINGS_PHARYNGEAL_NUM_1_Y								121

#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_1_X					90
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_1_Y					35
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_2_X					100
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_2_Y					71
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_3_X					100
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_3_Y					94
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_4_X					364
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_4_Y					94
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_5_X					100
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_5_Y					117
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_6_X					80
#define SETTINGS_PHARYNGEAL_CONFIRM_TEXT_6_Y					198

#define SETTINGS_PHARYNGEAL_CONFIRM_NUM_1_X						324
#define SETTINGS_PHARYNGEAL_CONFIRM_NUM_1_Y						71
#define SETTINGS_PHARYNGEAL_CONFIRM_NUM_2_X						324
#define SETTINGS_PHARYNGEAL_CONFIRM_NUM_2_Y						94
#define SETTINGS_PHARYNGEAL_CONFIRM_NUM_3_X						324
#define SETTINGS_PHARYNGEAL_CONFIRM_NUM_3_Y						117

#define	SETTINGS_SUBGLOTTIC_TEXT_1_X							50
#define	SETTINGS_SUBGLOTTIC_TEXT_1_Y							48
#define	SETTINGS_SUBGLOTTIC_TEXT_2_X							50
#define	SETTINGS_SUBGLOTTIC_TEXT_2_Y							93
#define	SETTINGS_SUBGLOTTIC_TEXT_3_X							50
#define	SETTINGS_SUBGLOTTIC_TEXT_3_Y							121
#define	SETTINGS_SUBGLOTTIC_TEXT_4_X							344
#define	SETTINGS_SUBGLOTTIC_TEXT_4_Y							121
#define	SETTINGS_SUBGLOTTIC_TEXT_5_X							50
#define	SETTINGS_SUBGLOTTIC_TEXT_5_Y							149
#define	SETTINGS_SUBGLOTTIC_TEXT_6_X							50
#define	SETTINGS_SUBGLOTTIC_TEXT_6_Y							198

#define	SETTINGS_SUBGLOTTIC_NUM_1_X								298
#define	SETTINGS_SUBGLOTTIC_NUM_1_Y								121
#define	SETTINGS_SUBGLOTTIC_NUM_2_X								298
#define	SETTINGS_SUBGLOTTIC_NUM_2_Y								149

#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_1_X					90
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_1_Y					35
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_2_X					100
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_2_Y					71
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_3_X					100
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_3_Y					94
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_4_X					364
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_4_Y					94
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_5_X					100
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_5_Y					117
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_6_X					80
#define SETTINGS_SUBGLOTTIC_CONFIRM_TEXT_6_Y					198

#define SETTINGS_SUBGLOTTIC_CONFIRM_NUM_1_X						324
#define SETTINGS_SUBGLOTTIC_CONFIRM_NUM_1_Y						71
#define SETTINGS_SUBGLOTTIC_CONFIRM_NUM_2_X						324
#define SETTINGS_SUBGLOTTIC_CONFIRM_NUM_2_Y						94
#define SETTINGS_SUBGLOTTIC_CONFIRM_NUM_3_X						324
#define SETTINGS_SUBGLOTTIC_CONFIRM_NUM_3_Y						117

#define	SETTINGS_LAVAGE_TEXT_1_X								50
#define	SETTINGS_LAVAGE_TEXT_1_Y								48
#define	SETTINGS_LAVAGE_TEXT_2_X								50
#define	SETTINGS_LAVAGE_TEXT_2_Y								93
#define	SETTINGS_LAVAGE_TEXT_3_X								50
#define	SETTINGS_LAVAGE_TEXT_3_Y								121
#define	SETTINGS_LAVAGE_TEXT_4_X								344
#define	SETTINGS_LAVAGE_TEXT_4_Y								121
#define	SETTINGS_LAVAGE_TEXT_5_X								50
#define	SETTINGS_LAVAGE_TEXT_5_Y								213

#define	SETTINGS_LAVAGE_TEXT_6_X								50
#define	SETTINGS_LAVAGE_TEXT_6_Y								149
#define	SETTINGS_LAVAGE_TEXT_7_X								344
#define	SETTINGS_LAVAGE_TEXT_7_Y								149
#define	SETTINGS_LAVAGE_TEXT_8_X								50
#define	SETTINGS_LAVAGE_TEXT_8_Y								177
#define	SETTINGS_LAVAGE_TEXT_9_X								344
#define	SETTINGS_LAVAGE_TEXT_9_Y								177



#define	SETTINGS_LAVAGE_NUM_1_X									298
#define	SETTINGS_LAVAGE_NUM_1_Y									121
#define	SETTINGS_LAVAGE_NUM_2_X									308
#define	SETTINGS_LAVAGE_NUM_2_Y									93
#define	SETTINGS_LAVAGE_NUM_3_X									318
#define	SETTINGS_LAVAGE_NUM_3_Y									121

#define	SETTINGS_LAVAGE_NUM_4_X									298
#define	SETTINGS_LAVAGE_NUM_4_Y									149
#define	SETTINGS_LAVAGE_NUM_5_X									298
#define	SETTINGS_LAVAGE_NUM_5_Y									177



#define SETTINGS_LAVAGE_CONFIRM_TEXT_1_X						90
#define SETTINGS_LAVAGE_CONFIRM_TEXT_1_Y						35
#define SETTINGS_LAVAGE_CONFIRM_TEXT_2_X						80
#define SETTINGS_LAVAGE_CONFIRM_TEXT_2_Y						71
#define SETTINGS_LAVAGE_CONFIRM_TEXT_3_X						80
#define SETTINGS_LAVAGE_CONFIRM_TEXT_3_Y						94
#define SETTINGS_LAVAGE_CONFIRM_TEXT_4_X						324
#define SETTINGS_LAVAGE_CONFIRM_TEXT_4_Y						94
#define SETTINGS_LAVAGE_CONFIRM_TEXT_5_X						80
#define SETTINGS_LAVAGE_CONFIRM_TEXT_5_Y						198

#define SETTINGS_LAVAGE_CONFIRM_TEXT_6_X						80
#define SETTINGS_LAVAGE_CONFIRM_TEXT_6_Y						117
#define SETTINGS_LAVAGE_CONFIRM_TEXT_7_X						324
#define SETTINGS_LAVAGE_CONFIRM_TEXT_7_Y						117
#define SETTINGS_LAVAGE_CONFIRM_TEXT_8_X						80
#define SETTINGS_LAVAGE_CONFIRM_TEXT_8_Y						140
#define SETTINGS_LAVAGE_CONFIRM_TEXT_9_X						324
#define SETTINGS_LAVAGE_CONFIRM_TEXT_9_Y						140

#define SETTINGS_LAVAGE_CONFIRM_NUM_1_X							284
#define SETTINGS_LAVAGE_CONFIRM_NUM_1_Y							71
#define SETTINGS_LAVAGE_CONFIRM_NUM_2_X							284
#define SETTINGS_LAVAGE_CONFIRM_NUM_2_Y							94

#define SETTINGS_LAVAGE_CONFIRM_NUM_3_X							284
#define SETTINGS_LAVAGE_CONFIRM_NUM_3_Y							117
#define SETTINGS_LAVAGE_CONFIRM_NUM_4_X							284
#define SETTINGS_LAVAGE_CONFIRM_NUM_4_Y							140




#define SETTINGS_DATA_RETRIVE_TEXT_1_X							155
#define SETTINGS_DATA_RETRIVE_TEXT_1_Y							35
#define SETTINGS_DATA_RETRIVE_TEXT_2_X							150//60
#define SETTINGS_DATA_RETRIVE_TEXT_2_Y							198
#define SETTINGS_DATA_RETRIVE_UP_ICON_X							410
#define SETTINGS_DATA_RETRIVE_UP_ICON_Y							90
#define SETTINGS_DATA_RETRIVE_DOWN_ICON_X						410
#define SETTINGS_DATA_RETRIVE_DOWN_ICON_Y						150
#define DATA_RETRIEVE_TIME_X									148
#define DATA_RETRIEVE_DATE_X									40
#define DATA_RETRIEVE_DATA_X									250
#define DATA_RETRIEVE_ROW1_Y									90
#define DATA_RETRIEVE_ROW2_Y									120
#define DATA_RETRIEVE_ROW3_Y									150

#define SETTINGS_QUICK_ASSIST_TEXT_1_X							50
#define SETTINGS_QUICK_ASSIST_TEXT_1_Y							48
#define SETTINGS_QUICK_ASSIST_TEXT_2_X							50
#define SETTINGS_QUICK_ASSIST_TEXT_2_Y							93
#define SETTINGS_QUICK_ASSIST_TEXT_3_X							50
#define SETTINGS_QUICK_ASSIST_TEXT_3_Y							121
#define SETTINGS_QUICK_ASSIST_TEXT_4_X							50
#define SETTINGS_QUICK_ASSIST_TEXT_4_Y							149
#define SETTINGS_QUICK_ASSIST_TEXT_5_X							50
#define SETTINGS_QUICK_ASSIST_TEXT_5_Y							177
#define SETTINGS_QUICK_ASSIST_TEXT_6_X							50
#define SETTINGS_QUICK_ASSIST_TEXT_6_Y							213

#define SETTINGS_COLL_CONT_TEXT_1_X								60
#define SETTINGS_COLL_CONT_TEXT_1_Y								80
#define SETTINGS_COLL_CONT_TEXT_2_X								110
#define SETTINGS_COLL_CONT_TEXT_2_Y								110
#define SETTINGS_COLL_CONT_TEXT_3_X								90
#define SETTINGS_COLL_CONT_TEXT_3_Y								198

#define SETTINGS_REPLACE_LAVAGE_FLUID_TEXT_1_X					130
#define SETTINGS_REPLACE_LAVAGE_FLUID_TEXT_1_Y					90
#define SETTINGS_REPLACE_LAVAGE_FLUID_TEXT_2_X					90
#define SETTINGS_REPLACE_LAVAGE_FLUID_TEXT_2_Y					198

#define SETTINGS_REPLACE_VAPLUMEN_TEXT_1_X						100
#define SETTINGS_REPLACE_VAPLUMEN_TEXT_1_Y						100
#define SETTINGS_REPLACE_VAPLUMEN_TEXT_2_X						90
#define SETTINGS_REPLACE_VAPLUMEN_TEXT_2_Y						198

#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_1_X					50
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_1_Y					48
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_2_X					50
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_2_Y					84
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_3_X					50
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_3_Y					107//112
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_4_X					50
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_4_Y					135//140
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_5_X					50
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_5_Y					163//168
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_6_X					50
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_6_Y					196
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_7_X					90
#define SETTINGS_DETACH_PATIENT_STEPS_TEXT_7_Y					213

#define SETTINGS_SYSTEM_TEXT_0_X								50
#define SETTINGS_SYSTEM_TEXT_0_Y								48
#define SETTINGS_SYSTEM_TEXT_1_X								50
#define SETTINGS_SYSTEM_TEXT_1_Y								93
#define SETTINGS_SYSTEM_TEXT_2_X								50
#define SETTINGS_SYSTEM_TEXT_2_Y								121
#define SETTINGS_SYSTEM_TEXT_3_X								50
#define SETTINGS_SYSTEM_TEXT_3_Y								149
#define SETTINGS_SYSTEM_TEXT_4_X								50
#define SETTINGS_SYSTEM_TEXT_4_Y								177
#define SETTINGS_SYSTEM_TEXT_5_X								50
#define SETTINGS_SYSTEM_TEXT_5_Y								213

#define SETTINGS_SYSTEM_NUM_1_X									298
#define SETTINGS_SYSTEM_NUM_1_Y									93
#define SETTINGS_SYSTEM_NUM_2_X									298
#define SETTINGS_SYSTEM_NUM_2_Y									121
#define SETTINGS_SYSTEM_NUM_3_X									298
#define SETTINGS_SYSTEM_NUM_3_Y									149
#define SETTINGS_SYSTEM_NUM_4_X									298
#define SETTINGS_SYSTEM_NUM_4_Y									177

#define SETTINGS_SYSTEM_CONFIRM_TEXT_1_X						90
#define SETTINGS_SYSTEM_CONFIRM_TEXT_1_Y						35
#define SETTINGS_SYSTEM_CONFIRM_TEXT_2_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_2_Y						71
#define SETTINGS_SYSTEM_CONFIRM_TEXT_3_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_3_Y						94
#define SETTINGS_SYSTEM_CONFIRM_TEXT_4_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_4_Y						117
#define SETTINGS_SYSTEM_CONFIRM_TEXT_5_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_5_Y						140
#define SETTINGS_SYSTEM_CONFIRM_TEXT_6_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_6_Y						163
#define SETTINGS_SYSTEM_CONFIRM_TEXT_7_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_7_Y						186
#define SETTINGS_SYSTEM_CONFIRM_TEXT_8_X						80
#define SETTINGS_SYSTEM_CONFIRM_TEXT_8_Y						209
#define SETTINGS_SYSTEM_CONFIRM_TEXT_9_X						90
#define SETTINGS_SYSTEM_CONFIRM_TEXT_9_Y						239
#define SETTINGS_SYSTEM_CONFIRM_NUM_1_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_1_Y							71
#define SETTINGS_SYSTEM_CONFIRM_NUM_2_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_2_Y							94
#define SETTINGS_SYSTEM_CONFIRM_NUM_3_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_3_Y							117
#define SETTINGS_SYSTEM_CONFIRM_NUM_4_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_4_Y							140
#define SETTINGS_SYSTEM_CONFIRM_NUM_5_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_5_Y							163
#define SETTINGS_SYSTEM_CONFIRM_NUM_6_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_6_Y							186
#define SETTINGS_SYSTEM_CONFIRM_NUM_7_X							324
#define SETTINGS_SYSTEM_CONFIRM_NUM_7_Y							209

#define SETTINGS_SYSTEM_SHUTDOWN_CONFIRM_TEXT_1_X 				125
#define SETTINGS_SYSTEM_SHUTDOWN_CONFIRM_TEXT_1_Y				110
#define SETTINGS_SYSTEM_SHUTDOWN_CONFIRM_TEXT_2_X 				90
#define SETTINGS_SYSTEM_SHUTDOWN_CONFIRM_TEXT_2_Y				198

#define PAUSE_MAIN_TEXT_1_X										160
#define PAUSE_MAIN_TEXT_1_Y										48
#define PAUSE_MAIN_TEXT_2_X										140
#define PAUSE_MAIN_TEXT_2_Y										198

#define PAUSE_UNATTENDED_ALERT_TEXT_1_X							160
#define PAUSE_UNATTENDED_ALERT_TEXT_1_Y							40
#define PAUSE_UNATTENDED_ALERT_TEXT_2_X							50
#define PAUSE_UNATTENDED_ALERT_TEXT_2_Y							68
#define PAUSE_UNATTENDED_ALERT_TEXT_3_X							30
#define PAUSE_UNATTENDED_ALERT_TEXT_3_Y							208
#define PAUSE_UNATTENDED_ALERT_DISPLAY_DUMMY_ROW				93 /* Row 0 is not used*/
#define PAUSE_UNATTENDED_ALERT_DISPLAY_ROW1_Y					93
#define PAUSE_UNATTENDED_ALERT_DISPLAY_ROW2_Y					113
#define PAUSE_UNATTENDED_ALERT_DISPLAY_ROW3_Y					133
#define PAUSE_UNATTENDED_ALERT_DISPLAY_ROW4_Y					153
#define PAUSE_UNATTENDED_ALERT_DISPLAY_ROW5_Y					173
#define PAUSE_UNATTENDED_ALERT_DISPLAY_ID_X						255//350//45
#define PAUSE_UNATTENDED_ALERT_DISPLAY_TIME_X					150//280
#define PAUSE_UNATTENDED_ALERT_DISPLAY_DATE_X					35//350

//other definitions
#define BLACK													0x0001
#define WHITE													0xFFFF
#define BLUE													0x08C5
#define DARKBLUE												0x0843
#define LIGHTBLUE												0x02F3
#define MIDBLUE													0x01CC
#define EXPBLUE													0x0291
#define GREY													0x3A08
#define ORANGE													0xF4A3
#define LIGHTGREY												0x8410
#define MEDGREEN												0x03AE
#define RED														0xF800
#define LIGHT_BLUE												0x2CBF
#define YELLOW													0xFFE0
#define EXMP													0xF945
#define BORDERGREY												0xDEFB
#define CYAN													0x07FF

#define INACTIVE_SCREEN_TOP_TILE_GREY							0x3186
#define ACTIVE_SCREEN_TOP_TILE_BLUE								0x0A4E
#define ACTIVE_SCREEN_PRESSURE_UPDATE_BG_BLUE					0x0863

#define FB_MODE													0xC5
#define F_MODE													0x85

#define HOUR_12_FORMAT											0x12
#define HOUR_12_FORMAT_89										0x18

#define HOUR_8													0x20
#define HOUR_9													0x21

#define ROW1													0
#define ROW2													1
#define ROW3													2
#define ROW4													3
#define ROW5													4
#define ROW6													5
#define ROW7													6
#define ROW8													7
#define ROW9													8
#define ROW10													9

#define FIRMWARE_VERSION_X										380
#define FIRMWARE_VERSION_Y										244

#define RTC_TIME_X												150
#define RTC_TIME_Y												3

#define TOTAL_TYPE_OF_SUCTIONS							2

#define TOTAL_NUM_OF_TUBES								2

#define SUBGLOTTIC_SUCTION								0
#define OROPHARYNGEAL_SUCTION							1
#define CHLORHEXIDINE_SUCTION							2
#define INSIDE_ET_TUBE_SUCTION							3
#define BRUSHING_PROTOCOL								4
#define PORT_BLOCK										5
#define LAVAGE_PRESSURE									6

#define SETTING_TARGET_PRESSURE							0
#define SUCTION_PRESSURE								1

void LCD_Initialization(void);
void open_win(const char* window_name);
void set_visible_icon(const char *icon_name, uint16_t visible);
void set_text(const char* widget_type, const char* widget_name, const char* text);
void set_image(const char* widget_name, const char* image_name);
void LCD_DisplayText(uint8_t ui8TextDisplayMode, uint16_t ui16X, uint16_t ui16Y, const char *pi8String, uint8_t ui8FontIndex, uint16_t ui16FColor, uint16_t ui16BColor);
void LCD_DisplayNumber(uint8_t ui8TextDisplayMode, uint16_t ui16X, uint16_t ui16Y, uint16_t ui16Value, uint8_t ui8FontIndex, uint16_t ui16FColor, uint16_t ui16BColor);
void LCD_DisplayImage(uint16_t ui16index);
void LCD_DisplayIcon(uint16_t ui16X, uint16_t ui16Y, uint16_t ui16Index);
void LCD_DisplayNewPatientSelection(void);
void LCD_DisplayNewPatientSelectionMenu(uint8_t ui8Num);
void LCD_DisplayConfirmNewPatient(void);
void LCD_DisplayFlashErasingScreen(void);
void LCD_DisplayClampTubesMain(void);
void LCD_DisplayClampTubesPause(void);
void LCD_DisplayUnclampTubes(void);
void LCD_DisplayLowBattery(void);
void LCD_DisplayAlertScreen1(void);
void LCD_DisplayAlertScreen2(void);
void LCD_DisplayBatteryCharge(uint8_t ui8BatteryCharge);
void LCD_DisplaySettingSystemMenu(uint8_t ui8Row, uint8_t ui8RightArrowStatus, uint8_t ui8LeftArrowStatus,uint8_t ui8RowIconRefreshFlag);
void LCD_ConfirmParameterAndBeginSuctionScreen(void);
void LCD_DisplayNewMainSettingsPage1(void);
void LCD_DisplayNewMainSettingsPage2(void);
void LCD_DisplayPharyngealPortSuction(void);
void LCD_DisplaySubglotticPortSuction(void);
void LCD_DisplayInsideEtTubeSuction(void);
void LCD_DisplayWaitScreen(void);
void LCD_DisplayBeginSuction(void);
void LCD_DisplayPauseScreen(void);

//extra definitions
#define LCD_HANDSHAKE_CMD										0x00
#define LCD_HEADER												0xAA
#define LCD_CUSTOM_TEXT_DISPLAY_CMD								0x98
#define LCD_FONT_LIBRARY_SELECT_CMD								0x03
#define LCD_SET_FB_COLOR_CMD									0x40
#define LCD_DISPLAY_IMAGE_CMD									0x70
#define LCD_DISPLAY_ICON_CMD									0x99
#define LCD_SET_BRIGHTNESS_CMD									0x5F
#define LCD_FILL_AREA_CMD										0x64
#define LCD_DEFAULT_12X24_TEXT_DISPLAY_CMD						0x55
#define LCD_DEFAULT_8X16_TEXT_DISPLAY_CMD						0x54

#define LCD_FOOTER_LEN											4
#define LCD_HANDSHAKE_CMD_LEN									6
#define LCD_SET_FB_COLOR_CMD_LEN								10
#define LCD_DISPLAY_IMAGE_CMD_LEN								8
#define LCD_DISPLAY_ICON_CMD_LEN								12
#define LCD_SET_BRIGHTNESS_CMD_LEN								7
#define LCD_FILL_AREA_CMD_LEN									12
#define LCD_DISPLAY_REMAINING_TIME_CMD_LEN						20
#define DATA_RETRIEVE_TIME_CMD_LEN								18
#define DATA_RETRIEVE_DATE_CMD_LEN								21//20

#define LCD_8X16_FONT_INDEX										0x21
#define LCD_12X24_FONT_INDEX									0x22
#define LCD_16X32_FONT_INDEX									0x23
#define LCD_24X48_FONT_INDEX									0x24
#define LCD_32X64_FONT_INDEX									0x25

#define LCD_MIN_BRIGHTNESS										0x06
#define LCD_MAX_BRIGHTNESS										0x64
#endif /* INC_LCD_H_ */
